class FillPerks < ActiveRecord::Migration
  def change
    Perk.create(name: 'Астральное Пламя', js_class: 'Perks.AstralFlame')
    Perk.create(name: 'Благоволение Корда', js_class: 'Perks.GraceOfKord')
    Perk.create(name: 'Благословение Королевы Воронов', js_class: 'Perks.GraceOfRavenQueen')
    Perk.create(name: 'Боевые Рефлексы', js_class: 'Perks.CombatReflexes')
    Perk.create(name: 'Быстрое Выхватывание', js_class: 'Perks.InstantDraw')
    Perk.create(name: 'Быстрый Бегун', js_class: 'Perks.FastRunner')
    Perk.create(name: 'Владение Оружием', js_class: 'Perks.WeaponProficiency')
    Perk.create(name: 'Владение Щитом (лёгкий)', js_class: 'Perks.LightShieldProficiency')
    Perk.create(name: 'Владение Щитом (тяжёлый)', js_class: 'Perks.HeavyShieldProficiency')
    Perk.create(name: 'Всплеск Действий', js_class: 'Perks.ActionBurst')
    Perk.create(name: 'Гармония Эратис', js_class: 'Perks.EratisHarmony')
    Perk.create(name: 'Групповая Проницательность', js_class: 'Perks.GroupInsight')
    Perk.create(name: 'Дальнее Метание', js_class: 'Perks.FarThrowing')
    Perk.create(name: 'Дальний Выстрел', js_class: 'Perks.FarShot')
    Perk.create(name: 'Жгучая Буря', js_class: 'Perks.BurningStorm')
    Perk.create(name: 'Закольщик', js_class: 'Perks.Stabber')
    Perk.create(name: 'Защита Бахамута', js_class: 'Perks.ProtectionOfBahamut')
    Perk.create(name: 'Защита С Двумя Оружиями', js_class: 'Perks.DualWieldProtection')
    Perk.create(name: 'Защитная Подвижность', js_class: 'Perks.ProtectiveMoves')
    Perk.create(name: 'Зимний', js_class: 'Perks.Winterborn')
    Perk.create(name: 'Крепкое Тело', js_class: 'Perks.SturdyBody')
    Perk.create(name: 'Кровь Адского Пламени', js_class: 'Perks.HellfireBlood')
    Perk.create(name: 'Лечащие Руки', js_class: 'Perks.HealingHands')
    Perk.create(name: 'Лёгкая Поступь', js_class: 'Perks.Lightfoot')
    Perk.create(name: 'Ловкий Клинок', js_class: 'Perks.AgileBlade')
    Perk.create(name: 'Мастер На Все Руки', js_class: 'Perks.SwissKnife')
    Perk.create(name: 'Мастер Побега', js_class: 'Perks.Escapist')
    Perk.create(name: 'Меткий Охотник', js_class: 'Perks.PreciseHunter')
    Perk.create(name: 'Милость Кореллона', js_class: 'Perks.GraceOfKorellon')
    Perk.create(name: 'Мощный Вызов', js_class: 'Perks.PowerTaunt')
    Perk.create(name: 'Настороженность', js_class: 'Perks.Awareness')
    Perk.create(name: 'Неистовство Драконорождённого', js_class: 'Perks.DragonbornRage')
    Perk.create(name: 'Неожиданный Нокдаун', js_class: 'Perks.UnexpectedKnockdown')
    Perk.create(name: 'Ношение Доспехов (из шкур)', js_class: 'Perks.HideArmorProficiency')
    Perk.create(name: 'Ношение Доспехов (кожаный)', js_class: 'Perks.LeatherArmorProficiency')
    Perk.create(name: 'Ношение Доспехов (кольчужный)', js_class: 'Perks.MailArmorProficiency')
    Perk.create(name: 'Ношение Доспехов (латный)', js_class: 'Perks.PlateArmorProficiency')
    Perk.create(name: 'Ношение Доспехов (чешуйчатый)', js_class: 'Perks.ScaleArmorProficiency')
    Perk.create(name: 'Отвлекающий Щит', js_class: 'Perks.DistractingShield')
    Perk.create(name: 'Отражение Сеанин', js_class: 'Perks.ReflectionOfSeanin')
    Perk.create(name: 'Потерявшийся В Толпе', js_class: 'Perks.LostInCrowd')
    Perk.create(name: 'Проворный Охотник', js_class: 'Perks.AgileHunter')
    Perk.create(name: 'Проворство Полуросликов', js_class: 'Perks.HalflingSpeed')
    Perk.create(name: 'Провоцированный Клинок', js_class: 'Perks.ProvokedBlade')
    Perk.create(name: 'Продление Превосходства', js_class: 'Perks.SuperiorityProlongation')
    Perk.create(name: 'Прыгун В Длину', js_class: 'Perks.LengthJumper')
    Perk.create(name: 'Расширенная Книга Заклинаний', js_class: 'Perks.EnhancedSpellbook')
    Perk.create(name: 'Ритуальный Заклинатель', js_class: 'Perks.RitualCaster')
    Perk.create(name: 'Самообладание Йоун', js_class: 'Perks.YounComposure')
    Perk.create(name: 'Силовая Атака', js_class: 'Perks.PowerAttack')
    Perk.create(name: 'Силовой Бросок', js_class: 'Perks.PowerCharge')
    Perk.create(name: 'Сияние Пелора', js_class: 'Perks.PelorShining')
    Perk.create(name: 'Смертоносный Охотник', js_class: 'Perks.DeadlyHunter')
    Perk.create(name: 'Спасение Авандры', js_class: 'Perks.AvandraRescue')
    Perk.create(name: 'Сражение Верхом', js_class: 'Perks.MountedCombat')
    Perk.create(name: 'Сражение С Двумя Оружиями', js_class: 'Perks.DualWield')
    Perk.create(name: 'Стойкий', js_class: 'Perks.Sturdy')
    Perk.create(name: 'Тактическое Нападение', js_class: 'Perks.TacticalAttack')
    Perk.create(name: 'Тёмная Ярость', js_class: 'Perks.DarkRage')
    Perk.create(name: 'Течение Мелоры', js_class: 'Perks.MeloraFlow')
    Perk.create(name: 'Толчок Щитом', js_class: 'Perks.ShieldBash')
    Perk.create(name: 'Тренировка Навыка', js_class: 'Perks.SkillTraining')
    Perk.create(name: 'Тренировка С Оружием Дварфов', js_class: 'Perks.DwarfWeaponTraining')
    Perk.create(name: 'Увеличенное Дыхание Дракона', js_class: 'Perks.ImprovedDragonBreath')
    Perk.create(name: 'Уверенный Альпинист', js_class: 'Perks.SkilledClimber')
    Perk.create(name: 'Уклонение От Великанов', js_class: 'Perks.GiantDodge')
    Perk.create(name: 'Улучшенная Опустошающая Судьба', js_class: 'Perks.ImprovedDevastatingDestiny')
    Perk.create(name: 'Улучшенная Инициатива', js_class: 'Perks.ImprovedInitiative')
    Perk.create(name: 'Улучшенное Тёмное Благословение', js_class: 'Perks.ImprovedDarkBless')
    Perk.create(name: 'Улучшенный Туманный Шаг', js_class: 'Perks.ImprovedShadowStep')
    Perk.create(name: 'Устранение Морадина', js_class: 'Perks.RemovalOfMoradin')
    Perk.create(name: 'Фокусировка На Навыке', js_class: 'Perks.SkillFocus')
    Perk.create(name: 'Фокусировка На Оружии', js_class: 'Perks.WeaponFocus')
    Perk.create(name: 'Человеческая Непоколебимость', js_class: 'Perks.HumanInflexibility')
    Perk.create(name: 'Чувства Драконорождённого', js_class: 'Perks.DragonbornFeelings')
    Perk.create(name: 'Эладринский Солдат', js_class: 'Perks.EladrinSoldier')
    Perk.create(name: 'Эльфийская Точность', js_class: 'Perks.ElvenPrecision')
    Perk.create(name: 'Языковед', js_class: 'Perks.Linguist')
    Perk.create(name: 'Яростный Напор', js_class: 'Perks.FuriousPush')
    Perk.create(name: 'Яростный Шторм', js_class: 'Perks.FuriousStorm')
  end
end
