json.title              weapon.title
json.id                 weapon.id
json.js_class           weapon.js_class
json.avatar_url         weapon.avatar.url(:thumb)
json.attack_char_from   weapon.attack_char_from
json.attack_char_to     weapon.attack_char_to
json.damage_dice        weapon.damage_dice
json.damage_count       weapon.damage_count
json.prof               weapon.prof
json.weapon_group_name	weapon.weapon_group.try(:name)
